// Reads the committed browser assets and regenerates html_report_assets.dart.
// Run after editing any file under lib/src/cli/report/assets/.
// Paths are anchored to the repo root via Platform.script, so it works
// regardless of the current working directory.
import 'dart:io';

import 'package:path/path.dart' as p;

void main() {
  final root = p.dirname(
    p.dirname(Platform.script.toFilePath()),
  ); // tool/ -> root
  final dir = p.join(root, 'lib/src/cli/report/assets');
  final css = File(p.join(dir, 'styles.css')).readAsStringSync();
  final js = File(p.join(dir, 'app.js')).readAsStringSync();
  final tmpl = File(p.join(dir, 'index.html.tmpl')).readAsStringSync();
  for (final s in [css, js, tmpl]) {
    if (s.contains("'''")) {
      stderr.writeln("Asset contains ''' — cannot raw-embed.");
      exit(1);
    }
  }
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_report_assets.dart — do not edit.')
    ..writeln('// Source: lib/src/cli/report/assets/')
    ..writeln()
    ..writeln("const String stylesCss = r'''$css''';")
    ..writeln()
    ..writeln("const String appJs = r'''$js''';")
    ..writeln()
    ..writeln("const String indexHtmlTemplate = r'''$tmpl''';");
  File(
    p.join(root, 'lib/src/cli/report/html_report_assets.dart'),
  ).writeAsStringSync(out.toString());
  stdout.writeln('Wrote lib/src/cli/report/html_report_assets.dart');
}
