// ALEA — `.alea.yaml` generator for `aflow init --template config`.
//
// Pure function: given parsed pubspec data and a layer scan result, emits the
// YAML content of a starter `.alea.yaml`. Every generated field carries a
// comment documenting its origin so the consumer (and a future reviewer)
// can tell apart auto-detected values from defaults and from placeholders
// that need human attention.
//
// Detection scope is deliberately conservative (see ConfigGenerationInput
// docs). Anything not auto-detected becomes an explicit PLACEHOLDER block
// with editing instructions and a pointer to
// docs/proposals/0001-adoption-flow-overhaul.md (Item A — Diagnostics).
//
// This file has no I/O — it operates on inputs and returns a String. The
// caller (init_command.dart) is responsible for writing the result.

import 'pubspec_reader.dart';
import 'layer_scanner.dart';

class ConfigGenerationInput {
  const ConfigGenerationInput({
    required this.pubspec,
    required this.layers,
    required this.generatedAtUtc,
  });

  final PubspecData pubspec;
  final LayerPaths layers;

  /// ISO 8601 UTC timestamp stamped at the top of the generated YAML.
  /// Injectable so tests can pin a deterministic value.
  final DateTime generatedAtUtc;
}

class ConfigGenerator {
  const ConfigGenerator();

  /// Builds the YAML content. The result is a single String terminated by a
  /// newline.
  String generate(ConfigGenerationInput input) {
    final buf = StringBuffer();
    _writeHeader(buf, input);
    _writeProject(buf, input);
    _writeArchitecture(buf, input);
    _writeStateManagement(buf, input);
    _writeRouting(buf, input);
    _writeTheme(buf, input);
    _writeTesting(buf, input);
    _writeCoverage(buf);
    _writeTicketSource(buf);
    _writeDesignSource(buf);
    _writeMr(buf, input);
    _writePipeline(buf);
    _writeGates(buf);
    return buf.toString();
  }

  void _writeHeader(StringBuffer buf, ConfigGenerationInput i) {
    final ts = _formatIso8601(i.generatedAtUtc);
    buf
      ..writeln('# Generated by `aflow init --template config` on $ts.')
      ..writeln('# Source: pubspec.yaml (${i.pubspec.packageName}).')
      ..writeln('#')
      ..writeln('# Re-generate with: aflow init --template config --force')
      ..writeln('#')
      ..writeln('# Marker legend in this file:')
      ..writeln('#   `# inferred from <X>` — auto-detected from your project.')
      ..writeln('#   `# detected at <path>` — folder found by filesystem scan.')
      ..writeln(
        '#   `# default` — industry-standard fallback; adjust if needed.',
      )
      ..writeln(
        '#   `# PLACEHOLDER` — could not auto-detect; human action required.',
      )
      ..writeln()
      ..writeln('config_version: "1.0.0"')
      ..writeln();
  }

  void _writeProject(StringBuffer buf, ConfigGenerationInput i) {
    buf
      ..writeln('project:')
      ..writeln(
        '  package_name: ${i.pubspec.packageName}   # from pubspec.yaml::name',
      )
      ..writeln('  pubspec_path: pubspec.yaml')
      ..writeln();
  }

  void _writeArchitecture(StringBuffer buf, ConfigGenerationInput i) {
    buf
      ..writeln('architecture:')
      ..writeln('  layers:');
    _writeDomainLayer(buf, i.layers);
    _writeInfrastructureLayer(buf, i.layers);
    _writePresentationLayer(buf, i.layers);
    buf.writeln();
  }

  void _writeDomainLayer(StringBuffer buf, LayerPaths layers) {
    buf.writeln('    domain:');
    final path = layers.domainPath;
    if (path != null) {
      buf
        ..writeln('      paths: [$path]   # detected at $path')
        ..writeln(
          '      forbid_imports: ["package:flutter/"]   # default — keep domain pure',
        );
    } else {
      _writeLayerPlaceholder(
        buf,
        layerName: 'domain',
        canonicalSuggestion: 'lib/src/domain/',
        alternatives: const [
          'lib/domain/',
          'lib/src/dominio/                  (Spanish)',
          'lib/features/<feature>/domain/    (feature-first)',
        ],
      );
      buf.writeln(
        '      forbid_imports: ["package:flutter/"]   # default — keep domain pure',
      );
    }
  }

  void _writeInfrastructureLayer(StringBuffer buf, LayerPaths layers) {
    buf.writeln('    infrastructure:');
    final path = layers.infrastructurePath;
    if (path != null) {
      buf
        ..writeln('      paths: [$path]   # detected at $path')
        ..writeln('      may_import: [domain]   # default');
    } else {
      _writeLayerPlaceholder(
        buf,
        layerName: 'infrastructure',
        canonicalSuggestion: 'lib/src/infrastructure/',
        alternatives: const [
          'lib/infrastructure/',
          'lib/data/                         (Clean Architecture — rename key from `infrastructure` to `data` to match)',
          'lib/src/data/',
          'lib/features/<feature>/data/      (feature-first)',
        ],
      );
      buf.writeln('      may_import: [domain]   # default');
    }
  }

  void _writePresentationLayer(StringBuffer buf, LayerPaths layers) {
    buf.writeln('    presentation:');
    final path = layers.presentationPath;
    if (path != null) {
      buf
        ..writeln('      paths: [$path]   # detected at $path')
        ..writeln('      may_import: [domain]   # default');
    } else {
      _writeLayerPlaceholder(
        buf,
        layerName: 'presentation',
        canonicalSuggestion: 'lib/src/presentation/',
        alternatives: const [
          'lib/presentation/',
          'lib/src/ui/                       (older convention)',
          'lib/src/presentacion/             (Spanish)',
          'lib/features/<feature>/presentation/',
        ],
      );
      buf.writeln('      may_import: [domain]   # default');
    }
  }

  void _writeLayerPlaceholder(
    StringBuffer buf, {
    required String layerName,
    required String canonicalSuggestion,
    required List<String> alternatives,
  }) {
    buf
      ..writeln(
        '      # PLACEHOLDER — could not auto-detect a canonical $layerName folder.',
      )
      ..writeln('      # Common alternatives in real Flutter projects:');
    for (final alt in alternatives) {
      buf.writeln('      #   - $alt');
    }
    buf
      ..writeln(
        '      # Edit the path below (and the key name if your project uses a',
      )
      ..writeln(
        '      # different layer label like `data`). Repeated edits here',
      )
      ..writeln(
        '      # are the trigger to activate full layer detection — see',
      )
      ..writeln(
        '      # docs/proposals/0001-adoption-flow-overhaul.md (Item A).',
      )
      ..writeln('      paths: [$canonicalSuggestion]');
  }

  void _writeStateManagement(StringBuffer buf, ConfigGenerationInput i) {
    final style = i.pubspec.stateManagementStyle;
    final origin = i.pubspec.stateManagementOrigin;
    buf.writeln('state_management:');
    if (style != null && origin != null) {
      buf.writeln(
        '  style: $style   # inferred from pubspec.yaml::dependencies::$origin',
      );
    } else {
      buf
        ..writeln(
          '  # PLACEHOLDER — no known state-management dependency in pubspec.yaml.',
        )
        ..writeln(
          '  # Set one of: riverpod_manual | bloc | provider | getx | none',
        )
        ..writeln('  style: riverpod_manual');
    }
    buf.writeln();
  }

  void _writeRouting(StringBuffer buf, ConfigGenerationInput i) {
    final pkg = i.pubspec.routingPackage;
    final origin = i.pubspec.routingOrigin;
    buf.writeln('routing:');
    if (pkg != null && origin != null) {
      buf
        ..writeln(
          '  package: $pkg   # inferred from pubspec.yaml::dependencies::$origin',
        )
        ..writeln(
          '  router_path: lib/src/app/router.dart   # default — verify',
        );
    } else {
      buf
        ..writeln('  # PLACEHOLDER — no known routing package in pubspec.yaml.')
        ..writeln('  # Set one of: go_router | auto_route | none')
        ..writeln('  package: go_router')
        ..writeln('  router_path: lib/src/app/router.dart');
    }
    buf.writeln();
  }

  void _writeTheme(StringBuffer buf, ConfigGenerationInput i) {
    final themePath = i.layers.themePath;
    buf.writeln('theme:');
    if (themePath != null) {
      buf
        ..writeln('  path: $themePath   # detected at $themePath')
        ..writeln('  token_catalog:')
        ..writeln('    adapter: dart_source   # default')
        ..writeln('    source: $themePath');
    } else {
      buf
        ..writeln('  # PLACEHOLDER — could not auto-detect a theme folder.')
        ..writeln('  path: lib/src/theme/')
        ..writeln('  token_catalog:')
        ..writeln('    adapter: dart_source')
        ..writeln('    source: lib/src/theme/');
    }
    buf.writeln();
  }

  void _writeTesting(StringBuffer buf, ConfigGenerationInput i) {
    buf.writeln('testing:');
    if (i.pubspec.isFlutterProject) {
      buf.writeln(
        '  framework: flutter_test   # inferred from pubspec.yaml::dependencies::flutter',
      );
    } else {
      buf.writeln(
        '  framework: dart_test   # inferred — no Flutter dependency in pubspec.yaml',
      );
    }
    buf
      ..writeln('  fakes_path: test/fakes/   # default')
      ..writeln();
  }

  void _writeCoverage(StringBuffer buf) {
    buf
      ..writeln('coverage:')
      ..writeln('  thresholds:')
      ..writeln('    domain: 95           # industry baseline for domain logic')
      ..writeln(
        '    infrastructure: 80   # industry baseline for adapters / repos',
      )
      ..writeln('    presentation: 70     # industry baseline for UI')
      ..writeln();
  }

  void _writeTicketSource(StringBuffer buf) {
    buf
      ..writeln('ticket_source:')
      ..writeln(
        '  adapter: file   # default — switch to asana / linear / jira when integrated',
      )
      ..writeln();
  }

  void _writeDesignSource(StringBuffer buf) {
    buf
      ..writeln('design_source:')
      ..writeln(
        '  default: figma   # default — adjust if your team uses another source',
      )
      ..writeln();
  }

  void _writeMr(StringBuffer buf, ConfigGenerationInput i) {
    final testCmd = i.pubspec.isFlutterProject ? 'flutter test' : 'dart test';
    buf
      ..writeln('mr:')
      ..writeln('  policy: single-commit-amend                # default')
      ..writeln('  branch_pattern: "feature/{ticket_id}-{slug}"   # default')
      ..writeln(
        '  pre_push: [dart format ., dart analyze, $testCmd]   # default',
      )
      ..writeln();
  }

  void _writePipeline(StringBuffer buf) {
    buf
      ..writeln('pipeline:')
      ..writeln(
        '  default_mode: guided   # default — interactive checkpoints; switch to semi/auto when confident',
      )
      ..writeln('  modes_available: [guided, semi, auto]')
      ..writeln('  cost_warn_usd: 3.0')
      ..writeln('  cost_hard_stop_usd: 5.0')
      ..writeln();
  }

  void _writeGates(StringBuffer buf) {
    buf
      ..writeln('gates:')
      ..writeln('  domain: [domain]              # default')
      ..writeln('  infrastructure: [infra]       # default')
      ..writeln('  presentation: [presentation]  # default');
  }

  /// Formats a [DateTime] as `YYYY-MM-DDTHH:MM:SSZ`. Avoids dragging in a
  /// formatting package; the buf-and-pad approach is fine for an ISO 8601
  /// stamp in UTC.
  String _formatIso8601(DateTime utc) {
    String pad(int n) => n.toString().padLeft(2, '0');
    final u = utc.toUtc();
    return '${u.year.toString().padLeft(4, '0')}'
        '-${pad(u.month)}'
        '-${pad(u.day)}'
        'T${pad(u.hour)}'
        ':${pad(u.minute)}'
        ':${pad(u.second)}Z';
  }
}
