// ALEA — Templates for the riverpod_manual code-gen adapter.
//
// Each template is ONE whole multi-line string. The template engine does
// `{{variable}}` substitution; no concatenation, no string building. To
// change the generated layout, edit the constants below — no Dart logic
// needs to follow.

const String riverpodStateTemplate = '''
// Generated by ALEA (riverpod_manual). Do not edit by hand.
import 'package:meta/meta.dart';

/// Immutable state for the {{feature_human_name}} feature.
@immutable
class {{state_class}} {
  final bool loading;
  final String? error;

  const {{state_class}}({this.loading = false, this.error});

  {{state_class}} copyWith({bool? loading, String? error}) {
    return {{state_class}}(
      loading: loading ?? this.loading,
      error: error ?? this.error,
    );
  }
}
''';

const String riverpodNotifierTemplate = '''
// Generated by ALEA (riverpod_manual). Do not edit by hand.
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '{{state_import}}';

class {{notifier_class}} extends Notifier<{{state_class}}> {
  @override
  {{state_class}} build() => const {{state_class}}();

  void reset() => state = const {{state_class}}();
}

final {{provider_name}} =
    NotifierProvider<{{notifier_class}}, {{state_class}}>(
  {{notifier_class}}.new,
);
''';

const String riverpodScreenTemplate = '''
// Generated by ALEA (riverpod_manual). Do not edit by hand.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '{{notifier_import}}';

class {{screen_class}} extends ConsumerWidget {
  const {{screen_class}}({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch({{provider_name}});
    return Scaffold(
      appBar: AppBar(title: const Text('{{feature_human_name}}')),
      body: Center(
        child: state.loading
            ? const CircularProgressIndicator()
            : Text(state.error ?? '{{feature_human_name}} ready'),
      ),
    );
  }
}
''';
