// ALEA — Templates for the bloc code-gen adapter.
//
// Same architectural rules as riverpod_manual/templates.dart: each constant
// is one whole multi-line string; the engine substitutes `{{variable}}`
// placeholders.

const String blocStateTemplate = '''
// Generated by ALEA (bloc). Do not edit by hand.
import 'package:equatable/equatable.dart';

sealed class {{state_class}} extends Equatable {
  const {{state_class}}();
  @override
  List<Object?> get props => const [];
}

final class {{state_class}}Initial extends {{state_class}} {
  const {{state_class}}Initial();
}

final class {{state_class}}Loading extends {{state_class}} {
  const {{state_class}}Loading();
}

final class {{state_class}}Ready extends {{state_class}} {
  final String message;
  const {{state_class}}Ready(this.message);
  @override
  List<Object?> get props => [message];
}

final class {{state_class}}Failed extends {{state_class}} {
  final String error;
  const {{state_class}}Failed(this.error);
  @override
  List<Object?> get props => [error];
}
''';

const String blocEventTemplate = '''
// Generated by ALEA (bloc). Do not edit by hand.
import 'package:equatable/equatable.dart';

sealed class {{event_class}} extends Equatable {
  const {{event_class}}();
  @override
  List<Object?> get props => const [];
}

final class {{event_class}}Start extends {{event_class}} {
  const {{event_class}}Start();
}

final class {{event_class}}Reset extends {{event_class}} {
  const {{event_class}}Reset();
}
''';

const String blocBlocTemplate = '''
// Generated by ALEA (bloc). Do not edit by hand.
import 'package:bloc/bloc.dart';

import '{{state_import}}';
import '{{event_import}}';

class {{bloc_class}} extends Bloc<{{event_class}}, {{state_class}}> {
  {{bloc_class}}() : super(const {{state_class}}Initial()) {
    on<{{event_class}}Start>((event, emit) async {
      emit(const {{state_class}}Loading());
      emit(const {{state_class}}Ready('{{feature_human_name}} ready'));
    });
    on<{{event_class}}Reset>((event, emit) {
      emit(const {{state_class}}Initial());
    });
  }
}
''';

const String blocScreenTemplate = '''
// Generated by ALEA (bloc). Do not edit by hand.
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '{{bloc_import}}';
import '{{state_import}}';

class {{screen_class}} extends StatelessWidget {
  const {{screen_class}}({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider<{{bloc_class}}>(
      create: (_) => {{bloc_class}}(),
      child: Scaffold(
        appBar: AppBar(title: const Text('{{feature_human_name}}')),
        body: BlocBuilder<{{bloc_class}}, {{state_class}}>(
          builder: (context, state) {
            return Center(
              child: switch (state) {
                {{state_class}}Initial() => const Text('start'),
                {{state_class}}Loading() => const CircularProgressIndicator(),
                {{state_class}}Ready(:final message) => Text(message),
                {{state_class}}Failed(:final error) => Text(error),
              },
            );
          },
        ),
      ),
    );
  }
}
''';
